### ISSUE TITLE
review the OpenSRP tech overview

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp.github.io#5]
@rowo, please have a look at this document.

https://docs.google.com/document/d/1hUzDYkt4Zr-YhpFfILrIT8ZtNI1jiTKVyOgRTjvnzeU/edit#heading=h.ka0ghalk6cp5

**Comment by rowo** [comment]
@ndisha this is for the website right? Can you make this more website-like? Meaning:
- Only use real content you want on there. Please do what you need to in order to achieve final content by end of the week.
- Provide a page title
- Use appropriate header tags. Right now there's an all caps header 1 and a non all caps header 1

Not sure what other feedback you are looking for. Please be sure the content in the graphics are final and agreed on since I'm going to redo them early next week. Please close this if the above feedback is sufficient.

**Comment by ndisha** [comment]
Thanks @rowo. 
The content is not final, @mberg is reviewing it. I will work on the rest of the items and update you.
